
    create TABLE dog(    id INT,
   name VARCHAR(49)  ,
    section VARCHAR(39) ,
    country VARCHAR(31) ,
    image VARCHAR(57) );


INSERT INTO dog VALUES
    (1,'ENGLISH POINTER','British and Irish Pointers and Setters','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/001g07.jpg'),
    (2,'ENGLISH SETTER','British and Irish Pointers and Setters','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/002g07.jpg'),
    (3,'KERRY BLUE TERRIER','Large and medium sized Terriers','IRELAND',NULL),
    (4,'CAIRN TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/004g03.jpg'),
    (5,'ENGLISH COCKER SPANIEL','Flushing Dogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/005g08.jpg'),
    (6,'GORDON SETTER','British and Irish Pointers and Setters','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/006g07.jpg'),
    (7,'AIREDALE TERRIER','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/007g03.jpg'),
    (8,'AUSTRALIAN TERRIER','Small sized Terriers','AUSTRALIA','http://www.fci.be/Nomenclature/Illustrations/008g03.jpg'),
    (9,'BEDLINGTON TERRIER','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/009g03.jpg'),
    (10,'BORDER TERRIER','Large and medium sized Terriers','GREAT BRITAIN',NULL),
    (11,'BULL TERRIER','Bull type Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/011g03.jpg'),
    (12,'FOX TERRIER (SMOOTH)','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/012g03.jpg'),
    (13,'ENGLISH TOY TERRIER (BLACK &TAN)','Toy Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/013g03.jpg'),
    (14,'SWEDISH VALLHUND','Nordic Watchdogs and Herders','SWEDEN','http://www.fci.be/Nomenclature/Illustrations/014g05.jpg'),
    (15,'BELGIAN SHEPHERD DOG','Sheepdogs','BELGIUM',NULL),
    (16,'OLD ENGLISH SHEEPDOG','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/016g01.jpg'),
    (17,'GRIFFON NIVERNAIS','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/017g06.jpg'),
    (19,'BRIQUET GRIFFON VENDEEN','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/019g06.jpg'),
    (20,'ARIEGEOIS','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/020g06.jpg'),
    (21,'GASCON SAINTONGEOIS','Scent hounds','FRANCE',NULL),
    (22,'GREAT GASCONY BLUE','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/022g06.jpg'),
    (24,'POITEVIN','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/024g06.jpg'),
    (25,'BILLY','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/025g06.jpg'),
    (28,'ARTOIS HOUND','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/028g06.jpg'),
    (30,'PORCELAINE','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/030g06.jpg'),
    (31,'SMALL BLUE GASCONY','Scent hounds','FRANCE',NULL),
    (32,'BLUE GASCONY GRIFFON','Scent hounds','FRANCE',NULL),
    (33,'GRAND BASSET GRIFFON VENDEEN','Scent hounds','FRANCE',NULL),
    (34,'NORMAN ARTESIEN BASSET','Scent hounds','FRANCE',NULL),
    (35,'BLUE GASCONY BASSET','Scent hounds','FRANCE',NULL),
    (36,'BASSET FAUVE DE BRETAGNE','Scent hounds','FRANCE',NULL),
    (37,'PORTUGUESE WATER DOG','Water Dogs','PORTUGAL','http://www.fci.be/Nomenclature/Illustrations/037g08.jpg'),
    (38,'WELSH CORGI (CARDIGAN)','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/038g01.jpg'),
    (39,'WELSH CORGI (PEMBROKE)','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/039g01.jpg'),
    (40,'IRISH SOFT COATED WHEATEN TERRIER','Large and medium sized Terriers','IRELAND',NULL),
    (41,'YUGOSLAVIAN SHEPHERD DOG - SHARPLANINA','Molossian type','MACEDONIA, SERBIA',NULL),
    (42,'JÄMTHUND','Nordic Hunting Dogs','SWEDEN','http://www.fci.be/Nomenclature/Illustrations/042g05.jpg'),
    (43,'BASENJI','Primitive type','CENTRAL AFRICA',NULL),
    (44,'BERGER DE BEAUCE','Sheepdogs','FRANCE',NULL),
    (45,'BERNESE MOUNTAIN DOG','Swiss Mountain- and Cattledogs','SWITZERLAND','http://www.fci.be/Nomenclature/Illustrations/045g02.jpg'),
    (46,'APPENZELL CATTLE DOG','Swiss Mountain- and Cattledogs','SWITZERLAND',NULL),
    (47,'ENTLEBUCH CATTLE DOG','Swiss Mountain- and Cattledogs','SWITZERLAND','http://www.fci.be/Nomenclature/Illustrations/047g02.jpg'),
    (48,'KARELIAN BEAR DOG','Nordic Hunting Dogs','FINLAND','http://www.fci.be/Nomenclature/Illustrations/048g05-1.jpg'),
    (49,'FINNISH SPITZ','Nordic Hunting Dogs','FINLAND','http://www.fci.be/Nomenclature/Illustrations/049g05-1.jpg'),
    (50,'NEWFOUNDLAND','Molossian type','CANADA',NULL),
    (51,'FINNISH HOUND','Scent hounds','FINLAND',NULL),
    (52,'POLISH HOUND','Scent hounds','POLAND','http://www.fci.be/Nomenclature/Illustrations/052g06.jpg'),
    (53,'KOMONDOR','Sheepdogs','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/053g01.jpg'),
    (54,'KUVASZ','Sheepdogs','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/054g01.jpg'),
    (55,'PULI','Sheepdogs','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/055g01.jpg'),
    (56,'PUMI','Sheepdogs','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/056g01.jpg'),
    (57,'HUNGARIAN SHORT-HAIRED POINTER (VIZSLA)','Continental Pointing Dogs','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/057g07.jpg'),
    (58,'GREAT SWISS MOUNTAIN DOG','Swiss Mountain- and Cattledogs','SWITZERLAND','http://www.fci.be/Nomenclature/Illustrations/058g02.jpg'),
    (59,'SWISS HOUND','Scent hounds','SWITZERLAND','http://www.fci.be/Nomenclature/Illustrations/059g06-1.jpg'),
    (60,'SMALL SWISS HOUND','Scent hounds','SWITZERLAND','http://www.fci.be/Nomenclature/Illustrations/060g06-1.jpg'),
    (61,'ST. BERNARD','Molossian type','SWITZERLAND','http://www.fci.be/Nomenclature/Illustrations/061g02-1.jpg'),
    (62,'COARSE-HAIRED STYRIAN HOUND','Scent hounds','AUSTRIA','http://www.fci.be/Nomenclature/Illustrations/062g06.jpg'),
    (63,'AUSTRIAN BLACK AND TAN HOUND','Scent hounds','AUSTRIA','http://www.fci.be/Nomenclature/Illustrations/063g06.jpg'),
    (64,'AUSTRIAN  PINSCHER','Pinscher and Schnauzer type','AUSTRIA',NULL),
    (65,'MALTESE','Bichons and related breeds','CENTRAL MEDITERRANEAN BASIN',NULL),
    (66,'FAWN BRITTANY GRIFFON','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/066g06.jpg'),
    (67,'PETIT BASSET GRIFFON VENDEEN','Scent hounds','FRANCE',NULL),
    (68,'TYROLEAN HOUND','Scent hounds','AUSTRIA',NULL),
    (70,'LAKELAND TERRIER','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/070g03.jpg'),
    (71,'MANCHESTER TERRIER','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/071g03.jpg'),
    (72,'NORWICH TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/072g03.jpg'),
    (73,'SCOTTISH TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/073g03.jpg'),
    (74,'SEALYHAM TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/074g03.jpg'),
    (75,'SKYE TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/075g03.jpg'),
    (76,'STAFFORDSHIRE BULL TERRIER','Bull type Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/076g03.jpg'),
    (77,'CONTINENTAL TOY SPANIEL','Continental Toy Spaniel and Russian Toy','BELGIUM, FRANCE',NULL),
    (78,'WELSH TERRIER','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/078g03.jpg'),
    (80,'GRIFFON BRUXELLOIS','Small Belgian Dogs','BELGIUM','http://www.fci.be/Nomenclature/Illustrations/080g09-1.jpg'),
    (81,'GRIFFON BELGE','Small Belgian Dogs','BELGIUM',NULL),
    (82,'PETIT BRABANÇON','Small Belgian Dogs','BELGIUM',NULL),
    (83,'SCHIPPERKE','Sheepdogs','BELGIUM',NULL),
    (84,'BLOODHOUND','Scent hounds','BELGIUM',NULL),
    (85,'WEST HIGHLAND WHITE TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/085g03.jpg'),
    (86,'YORKSHIRE TERRIER','Toy Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/086g03.jpg'),
    (87,'CATALAN SHEEPDOG','Sheepdogs','SPAIN',NULL),
    (88,'SHETLAND SHEEPDOG','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/088g01.jpg'),
    (89,'IBIZAN PODENCO','Primitive type - Hunting Dogs','SPAIN',NULL),
    (90,'BURGOS POINTING DOG','Continental Pointing Dogs','SPAIN',NULL),
    (91,'SPANISH MASTIFF','Molossian type','SPAIN',NULL),
    (92,'PYRENEAN MASTIFF','Molossian type','SPAIN',NULL),
    (93,'PORTUGUESE SHEEPDOG','Sheepdogs','PORTUGAL','http://www.fci.be/Nomenclature/Illustrations/093g01.jpg'),
    (94,'PORTUGUESE WARREN HOUND-PORTUGUESE PODENGO','Primitive type - Hunting Dogs','PORTUGAL','http://www.fci.be/Nomenclature/Illustrations/094g05-1.jpg'),
    (95,'BRITTANY SPANIEL','Continental Pointing Dogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/095g07.jpg'),
    (96,'RAFEIRO OF ALENTEJO','Molossian type','PORTUGAL','http://www.fci.be/Nomenclature/Illustrations/096g02.jpg'),
    (97,'GERMAN SPITZ','European Spitz','GERMANY','http://www.fci.be/Nomenclature/Illustrations/097g05-1.jpg'),
    (98,'GERMAN WIRE- HAIRED POINTING DOG','Continental Pointing Dogs','GERMANY','http://www.fci.be/Nomenclature/Illustrations/098g07.jpg'),
    (99,'WEIMARANER','Continental Pointing Dogs','GERMANY',NULL),
    (100,'WESTPHALIAN DACHSBRACKE','Scent hounds','GERMANY',NULL),
    (101,'FRENCH BULLDOG','Small Molossian type Dogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/101g09.jpg'),
    (102,'KLEINER MÜNSTERLÄNDER','Continental Pointing Dogs','GERMANY',NULL),
    (103,'GERMAN HUNTING TERRIER','Large and medium sized Terriers','GERMANY','http://www.fci.be/Nomenclature/Illustrations/103g03-1.jpg'),
    (104,'GERMAN SPANIEL','Flushing Dogs','GERMANY','http://www.fci.be/Nomenclature/Illustrations/104g08.jpg'),
    (105,'FRENCH WATER DOG','Water Dogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/105g08.jpg'),
    (106,'BLUE PICARDY SPANIEL','Continental Pointing Dogs','FRANCE',NULL),
    (107,'WIRE-HAIRED POINTING GRIFFON KORTHALS','Continental Pointing Dogs','FRANCE',NULL),
    (108,'PICARDY SPANIEL','Continental Pointing Dogs','FRANCE',NULL),
    (109,'CLUMBER SPANIEL','Flushing Dogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/109g08.jpg'),
    (110,'CURLY COATED RETRIEVER','Retrievers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/110g08.jpg'),
    (111,'GOLDEN RETRIEVER','Retrievers','GREAT BRITAIN',NULL),
    (113,'BRIARD','Sheepdogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/113g01.jpg'),
    (114,'PONT-AUDEMER SPANIEL','Continental Pointing Dogs','FRANCE',NULL),
    (115,'SAINT GERMAIN POINTER','Continental Pointing Dogs','FRANCE',NULL),
    (116,'DOGUE DE BORDEAUX','Molossian type','FRANCE','http://www.fci.be/Nomenclature/Illustrations/116g02.jpg'),
    (117,'DEUTSCH LANGHAAR','Continental Pointing Dogs','GERMANY','http://www.fci.be/Nomenclature/Illustrations/117g07.jpg'),
    (118,'LARGE MUNSTERLANDER','Continental Pointing Dogs','GERMANY','http://www.fci.be/Nomenclature/Illustrations/118g07.jpg'),
    (119,'GERMAN SHORT- HAIRED POINTING DOG','Continental Pointing Dogs','GERMANY','http://www.fci.be/Nomenclature/Illustrations/119g07.jpg'),
    (120,'IRISH RED SETTER','British and Irish Pointers and Setters','IRELAND',NULL),
    (121,'FLAT COATED RETRIEVER','Retrievers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/121g08.jpg'),
    (122,'LABRADOR RETRIEVER','Retrievers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/122g08.jpg'),
    (123,'FIELD SPANIEL','Flushing Dogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/123g08.jpg'),
    (124,'IRISH WATER SPANIEL','Water Dogs','IRELAND',NULL),
    (125,'ENGLISH SPRINGER SPANIEL','Flushing Dogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/125g08.jpg'),
    (126,'WELSH SPRINGER SPANIEL','Flushing Dogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/126g08.jpg'),
    (127,'SUSSEX SPANIEL','Flushing Dogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/127g08.jpg'),
    (128,'KING CHARLES SPANIEL','English Toy Spaniels','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/128g09.jpg'),
    (129,'SMÅLANDSSTÖVARE','Scent hounds','SWEDEN','http://www.fci.be/Nomenclature/Illustrations/129g06.jpg'),
    (130,'DREVER','Scent hounds','SWEDEN','http://www.fci.be/Nomenclature/Illustrations/130g06.jpg'),
    (131,'SCHILLERSTÖVARE','Scent hounds','SWEDEN','http://www.fci.be/Nomenclature/Illustrations/131g06.jpg'),
    (132,'HAMILTONSTÖVARE','Scent hounds','SWEDEN','http://www.fci.be/Nomenclature/Illustrations/132g06.jpg'),
    (133,'FRENCH POINTING DOG - GASCOGNE TYPE','Continental Pointing Dogs','FRANCE',NULL),
    (134,'FRENCH POINTING DOG - PYRENEAN TYPE','Continental Pointing Dogs','FRANCE',NULL),
    (135,'SWEDISH LAPPHUND','Nordic Watchdogs and Herders','SWEDEN',NULL),
    (136,'CAVALIER KING CHARLES SPANIEL','English Toy Spaniels','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/136g09.jpg'),
    (137,'PYRENEAN MOUNTAIN DOG','Molossian type','FRANCE','http://www.fci.be/Nomenclature/Illustrations/137g02.jpg'),
    (138,'PYRENEAN SHEEPDOG - SMOOTH FACED','Sheepdogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/138g01.jpg'),
    (139,'IRISH TERRIER','Large and medium sized Terriers','IRELAND',NULL),
    (140,'BOSTON TERRIER','Small Molossian type Dogs','UNITED STATES OF AMERICA',NULL),
    (141,'LONG-HAIRED PYRENEAN SHEEPDOG','Sheepdogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/141g01.jpg'),
    (142,'SLOVAKIAN CHUVACH','Sheepdogs','SLOVAKIA',NULL),
    (143,'DOBERMANN','Pinscher and Schnauzer type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/143g02.jpg'),
    (144,'BOXER','Molossian type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/144g02.jpg'),
    (145,'LEONBERGER','Molossian type','GERMANY',NULL),
    (146,'RHODESIAN RIDGEBACK','Related breeds','SOUTH AFRICA',NULL),
    (147,'ROTTWEILER','Molossian type','GERMANY',NULL),
    (148,'DACHSHUND',NULL,'GERMANY','http://www.fci.be/Nomenclature/Illustrations/148g04-1.jpg'),
    (149,'BULLDOG','Molossian type','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/149g02.jpg'),
    (150,'SERBIAN HOUND','Scent hounds','SERBIA','http://www.fci.be/Nomenclature/Illustrations/150g06.jpg'),
    (151,'ISTRIAN SHORT-HAIRED HOUND','Scent hounds','CROATIA','http://www.fci.be/Nomenclature/Illustrations/151g06.jpg'),
    (152,'ISTRIAN WIRE-HAIRED HOUND','Scent hounds','CROATIA','http://www.fci.be/Nomenclature/Illustrations/152g06.jpg'),
    (153,'DALMATIAN','Related breeds','CROATIA','http://www.fci.be/Nomenclature/Illustrations/153g06.jpg'),
    (154,'POSAVATZ HOUND','Scent hounds','CROATIA','http://www.fci.be/Nomenclature/Illustrations/154g06.jpg'),
    (155,'BOSNIAN BROKEN-HAIRED HOUND - CALLED BARAK','Scent hounds','BOSNIA AND HERZEGOVINA','http://www.fci.be/Nomenclature/Illustrations/155g06.jpg'),
    (156,'COLLIE ROUGH','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/156g01.jpg'),
    (157,'BULLMASTIFF','Molossian type','GREAT BRITAIN',NULL),
    (158,'GREYHOUND','Short-haired Sighthounds','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/158g10.jpg'),
    (159,'ENGLISH FOXHOUND','Scent hounds','GREAT BRITAIN',NULL),
    (160,'IRISH WOLFHOUND','Rough-haired Sighthounds','IRELAND',NULL),
    (161,'BEAGLE','Scent hounds','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/161g06.jpg'),
    (162,'WHIPPET','Short-haired Sighthounds','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/162g10.jpg'),
    (163,'BASSET HOUND','Scent hounds','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/163g06.jpg'),
    (164,'DEERHOUND','Rough-haired Sighthounds','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/164g10.jpg'),
    (165,'ITALIAN SPINONE','Continental Pointing Dogs','ITALY',NULL),
    (166,'GERMAN SHEPHERD DOG','Sheepdogs','GERMANY','http://www.fci.be/Nomenclature/Illustrations/166g01-1.jpg'),
    (167,'AMERICAN COCKER SPANIEL','Flushing Dogs','UNITED STATES OF AMERICA',NULL),
    (168,'DANDIE DINMONT TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/168g03.jpg'),
    (169,'FOX TERRIER (WIRE)','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/169g03.jpg'),
    (170,'CASTRO LABOREIRO DOG','Molossian type','PORTUGAL','http://www.fci.be/Nomenclature/Illustrations/170g02.jpg'),
    (171,'BOUVIER DES ARDENNES','Cattledogs (except Swiss Cattledogs)','BELGIUM',NULL),
    (172,'POODLE','Poodle','FRANCE','http://www.fci.be/Nomenclature/Illustrations/172g09.jpg'),
    (173,'ESTRELA MOUNTAIN DOG','Molossian type','PORTUGAL','http://www.fci.be/Nomenclature/Illustrations/173g02.jpg'),
    (175,'FRENCH SPANIEL','Continental Pointing Dogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/175g07.jpg'),
    (176,'PICARDY SHEEPDOG','Sheepdogs','FRANCE',NULL),
    (177,'ARIEGE POINTING DOG','Continental Pointing Dogs','FRANCE',NULL),
    (179,'BOURBONNAIS POINTING DOG','Continental Pointing Dogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/179g07.jpg'),
    (180,'AUVERGNE POINTER','Continental Pointing Dogs','FRANCE','http://www.fci.be/Nomenclature/Illustrations/180g07.jpg'),
    (181,'GIANT SCHNAUZER','Pinscher and Schnauzer type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/181g02.jpg'),
    (182,'SCHNAUZER','Pinscher and Schnauzer type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/182g02.jpg'),
    (183,'MINIATURE SCHNAUZER','Pinscher and Schnauzer type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/183g02.jpg'),
    (184,'GERMAN PINSCHER','Pinscher and Schnauzer type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/184g02.jpg'),
    (185,'MINIATURE PINSCHER','Pinscher and Schnauzer type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/185g02.jpg'),
    (186,'AFFENPINSCHER','Pinscher and Schnauzer type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/186g02.jpg'),
    (187,'PORTUGUESE POINTING DOG','Continental Pointing Dogs','PORTUGAL','http://www.fci.be/Nomenclature/Illustrations/187g07.jpg'),
    (188,'SLOUGHI','Short-haired Sighthounds','MOROCCO',NULL),
    (189,'FINNISH LAPPONIAN DOG','Nordic Watchdogs and Herders','FINLAND','http://www.fci.be/Nomenclature/Illustrations/189g05-1.jpg'),
    (190,'HOVAWART','Molossian type','GERMANY',NULL),
    (191,'BOUVIER DES FLANDRES','Cattledogs (except Swiss Cattledogs)','BELGIUM, FRANCE',NULL),
    (192,'KROMFOHRLÄNDER','Kromfohrländer','GERMANY','http://www.fci.be/Nomenclature/Illustrations/192g09.jpg'),
    (193,'BORZOI - RUSSIAN HUNTING SIGHTHOUND','Long-haired or fringed Sighthounds','RUSSIA','http://www.fci.be/Nomenclature/Illustrations/193g10.jpg'),
    (194,'BERGAMASCO SHEPHERD DOG','Sheepdogs','ITALY','http://www.fci.be/Nomenclature/Illustrations/194g01-1.jpg'),
    (195,'ITALIAN VOLPINO','European Spitz','ITALY',NULL),
    (196,'BOLOGNESE','Bichons and related breeds','ITALY',NULL),
    (197,'NEAPOLITAN MASTIFF','Molossian type','ITALY',NULL),
    (198,'ITALIAN ROUGH-HAIRED SEGUGIO','Scent hounds','ITALY',NULL),
    (199,'CIRNECO DELL''ETNA','Primitive type - Hunting Dogs','ITALY',NULL),
    (200,'ITALIAN SIGHTHOUND','Short-haired Sighthounds','ITALY',NULL),
    (201,'MAREMMA AND THE ABRUZZES SHEEPDOG','Sheepdogs','ITALY',NULL),
    (202,'ITALIAN POINTING DOG','Continental Pointing Dogs','ITALY','http://www.fci.be/Nomenclature/Illustrations/202g07.jpg'),
    (203,'NORWEGIAN HOUND','Scent hounds','NORWAY','http://www.fci.be/Nomenclature/Illustrations/203g06.jpg'),
    (204,'SPANISH HOUND','Scent hounds','SPAIN',NULL),
    (205,'CHOW CHOW','Asian Spitz and related breeds','CHINA','http://www.fci.be/Nomenclature/Illustrations/205g05.jpg'),
    (206,'JAPANESE CHIN','Japan Chin and Pekingese','JAPAN','http://www.fci.be/Nomenclature/Illustrations/206g09.jpg'),
    (207,'PEKINGESE','Japan Chin and Pekingese','CHINA','http://www.fci.be/Nomenclature/Illustrations/207g09.jpg'),
    (208,'SHIH TZU','Tibetan breeds','Tibet (China)','http://www.fci.be/Nomenclature/Illustrations/208g09.jpg'),
    (209,'TIBETAN TERRIER','Tibetan breeds','Tibet (China)','http://www.fci.be/Nomenclature/Illustrations/209g09.jpg'),
    (211,'CANADIAN ESKIMO DOG','Nordic Sledge Dogs','CANADA','http://www.fci.be/Nomenclature/Illustrations/211g05.jpg'),
    (212,'SAMOYED','Nordic Sledge Dogs','NORTHERN RUSSIA, SIBERIA','http://www.fci.be/Nomenclature/Illustrations/212g05.jpg'),
    (213,'HANOVERIAN SCENT HOUND','Leash (scent) Hounds','GERMANY','http://www.fci.be/Nomenclature/Illustrations/213g06-1.jpg'),
    (214,'HELLENIC HOUND','Scent hounds','GREECE',NULL),
    (215,'BICHON FRISE','Bichons and related breeds','BELGIUM, FRANCE','http://www.fci.be/Nomenclature/Illustrations/215g09-1.jpg'),
    (216,'PUDELPOINTER','Continental Pointing Dogs','GERMANY',NULL),
    (217,'BAVARIAN MOUNTAIN SCENT HOUND','Leash (scent) Hounds','GERMANY','http://www.fci.be/Nomenclature/Illustrations/217g06-1.jpg'),
    (218,'CHIHUAHUA','Chihuahueno','MEXICO','http://www.fci.be/Nomenclature/Illustrations/218g09-1.jpg'),
    (219,'FRENCH TRICOLOUR HOUND','Scent hounds','FRANCE',NULL),
    (220,'FRENCH WHITE & BLACK HOUND','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/220g06.jpg'),
    (221,'FRISIAN WATER DOG','Water Dogs','THE NETHERLANDS',NULL),
    (222,'STABIJHOUN','Continental Pointing Dogs','THE NETHERLANDS','http://www.fci.be/Nomenclature/Illustrations/222g07-1.jpg'),
    (223,'DUTCH SHEPHERD DOG','Sheepdogs','THE NETHERLANDS','http://www.fci.be/Nomenclature/Illustrations/223g01-1.jpg'),
    (224,'DRENTSCHE PARTRIDGE DOG','Continental Pointing Dogs','THE NETHERLANDS','http://www.fci.be/Nomenclature/Illustrations/224g07-1.jpg'),
    (225,'FILA BRASILEIRO','Molossian type','BRAZIL','http://www.fci.be/Nomenclature/Illustrations/225g02.jpg'),
    (226,'LANDSEER (EUROPEAN CONTINENTAL TYPE)','Molossian type','GERMANY, SWITZERLAND',NULL),
    (227,'LHASA APSO','Tibetan breeds','Tibet (China)','http://www.fci.be/Nomenclature/Illustrations/227g09.jpg'),
    (228,'AFGHAN HOUND','Long-haired or fringed Sighthounds','AFGHANISTAN','http://www.fci.be/Nomenclature/Illustrations/228g10.jpg'),
    (229,'SERBIAN TRICOLOUR HOUND','Scent hounds','SERBIA','http://www.fci.be/Nomenclature/Illustrations/229g06.jpg'),
    (230,'TIBETAN MASTIFF','Molossian type','Tibet (China)',NULL),
    (231,'TIBETAN SPANIEL','Tibetan breeds','Tibet (China)','http://www.fci.be/Nomenclature/Illustrations/231g09.jpg'),
    (232,'DEUTSCH STICHELHAAR','Continental Pointing Dogs','GERMANY','http://www.fci.be/Nomenclature/Illustrations/232g07.jpg'),
    (233,'LITTLE LION DOG','Bichons and related breeds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/233g09.jpg'),
    (234,'XOLOITZCUINTLE','Primitive type','MEXICO','http://www.fci.be/Nomenclature/Illustrations/234g05-1.jpg'),
    (235,'GREAT DANE','Molossian type','GERMANY','http://www.fci.be/Nomenclature/Illustrations/235g02.jpg'),
    (236,'AUSTRALIAN SILKY TERRIER','Toy Terriers','AUSTRALIA','http://www.fci.be/Nomenclature/Illustrations/236g03.jpg'),
    (237,'NORWEGIAN BUHUND','Nordic Watchdogs and Herders','NORWAY','http://www.fci.be/Nomenclature/Illustrations/237g05.jpg'),
    (238,'MUDI','Sheepdogs','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/238g01.jpg'),
    (239,'HUNGARIAN WIRE-HAIRED POINTER','Continental Pointing Dogs','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/239g07.jpg'),
    (240,'HUNGARIAN GREYHOUND','Short-haired Sighthounds','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/240g10.jpg'),
    (241,'HUNGARIAN HOUND - TRANSYLVANIAN SCENT HOUND','Scent hounds','HUNGARY','http://www.fci.be/Nomenclature/Illustrations/241g06.jpg'),
    (242,'NORWEGIAN ELKHOUND GREY','Nordic Hunting Dogs','NORWAY','http://www.fci.be/Nomenclature/Illustrations/242g05.jpg'),
    (243,'ALASKAN MALAMUTE','Nordic Sledge Dogs','UNITED STATES OF AMERICA',NULL),
    (244,'SLOVAKIAN HOUND','Scent hounds','SLOVAKIA',NULL),
    (245,'BOHEMIAN WIRE-HAIRED POINTING GRIFFON','Continental Pointing Dogs','CZECH REPUBLIC',NULL),
    (246,'CESKY TERRIER','Small sized Terriers','CZECH REPUBLIC','http://www.fci.be/Nomenclature/Illustrations/246g03.jpg'),
    (247,'ATLAS MOUNTAIN DOG (AIDI)','Molossian type','MOROCCO',NULL),
    (248,'PHARAOH HOUND','Primitive type','MALTA',NULL),
    (249,'MAJORCA MASTIFF','Molossian type','SPAIN',NULL),
    (250,'HAVANESE','Bichons and related breeds','CUBA',NULL),
    (251,'POLISH LOWLAND SHEEPDOG','Sheepdogs','POLAND','http://www.fci.be/Nomenclature/Illustrations/251g01.jpg'),
    (252,'TATRA SHEPHERD DOG','Sheepdogs','POLAND','http://www.fci.be/Nomenclature/Illustrations/252g01.jpg'),
    (253,'PUG','Small Molossian type Dogs','CHINA','http://www.fci.be/Nomenclature/Illustrations/253g09.jpg'),
    (254,'ALPINE DACHSBRACKE','Leash (scent) Hounds','AUSTRIA',NULL),
    (255,'AKITA','Asian Spitz and related breeds','JAPAN','http://www.fci.be/Nomenclature/Illustrations/255g05.jpg'),
    (257,'SHIBA','Asian Spitz and related breeds','JAPAN','http://www.fci.be/Nomenclature/Illustrations/257g05.jpg'),
    (259,'JAPANESE TERRIER','Small sized Terriers','JAPAN','http://www.fci.be/Nomenclature/Illustrations/259g03.jpg'),
    (260,'TOSA','Molossian type','JAPAN','http://www.fci.be/Nomenclature/Illustrations/260g02.jpg'),
    (261,'HOKKAIDO','Asian Spitz and related breeds','JAPAN','http://www.fci.be/Nomenclature/Illustrations/261g05.jpg'),
    (262,'JAPANESE SPITZ','Asian Spitz and related breeds','JAPAN','http://www.fci.be/Nomenclature/Illustrations/262g05.jpg'),
    (263,'CHESAPEAKE BAY RETRIEVER','Retrievers','UNITED STATES OF AMERICA',NULL);
INSERT INTO dog VALUES
    (264,'MASTIFF','Molossian type','GREAT BRITAIN',NULL),
    (265,'NORWEGIAN LUNDEHUND','Nordic Hunting Dogs','NORWAY','http://www.fci.be/Nomenclature/Illustrations/265g05.jpg'),
    (266,'HYGEN HOUND','Scent hounds','NORWAY','http://www.fci.be/Nomenclature/Illustrations/266g06.jpg'),
    (267,'HALDEN HOUND','Scent hounds','NORWAY','http://www.fci.be/Nomenclature/Illustrations/267g06.jpg'),
    (268,'NORWEGIAN ELKHOUND BLACK','Nordic Hunting Dogs','NORWAY','http://www.fci.be/Nomenclature/Illustrations/268g05.jpg'),
    (269,'SALUKI','Long-haired or fringed Sighthounds','MIDDLE EAST',NULL),
    (270,'SIBERIAN HUSKY','Nordic Sledge Dogs','UNITED STATES OF AMERICA',NULL),
    (271,'BEARDED COLLIE','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/271g01.jpg'),
    (272,'NORFOLK TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/272g03.jpg'),
    (273,'CANAAN DOG','Primitive type','ISRAEL',NULL),
    (274,'GREENLAND DOG','Nordic Sledge Dogs','GREENLAND','http://www.fci.be/Nomenclature/Illustrations/274g05.jpg'),
    (276,'NORRBOTTENSPITZ','Nordic Hunting Dogs','SWEDEN','http://www.fci.be/Nomenclature/Illustrations/276g05.jpg'),
    (277,'CROATIAN SHEPHERD DOG','Sheepdogs','CROATIA','http://www.fci.be/Nomenclature/Illustrations/277g01.jpg'),
    (278,'KARST SHEPHERD DOG','Molossian type','SLOVENIA','http://www.fci.be/Nomenclature/Illustrations/278g02.jpg'),
    (279,'MONTENEGRIN MOUNTAIN HOUND','Scent hounds','MONTENEGRO','http://www.fci.be/Nomenclature/Illustrations/279g06.jpg'),
    (281,'OLD DANISH POINTING DOG','Continental Pointing Dogs','DENMARK',NULL),
    (282,'GRAND GRIFFON VENDEEN','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/282g06.jpg'),
    (283,'COTON DE TULEAR','Bichons and related breeds','MADAGASCAR',NULL),
    (284,'LAPPONIAN HERDER','Nordic Watchdogs and Herders','FINLAND',NULL),
    (285,'SPANISH GREYHOUND','Short-haired Sighthounds','SPAIN',NULL),
    (286,'AMERICAN STAFFORDSHIRE TERRIER','Bull type Terriers','UNITED STATES OF AMERICA',NULL),
    (287,'AUSTRALIAN CATTLE DOG','Cattledogs (except Swiss Cattledogs)','AUSTRALIA','http://www.fci.be/Nomenclature/Illustrations/287g01.jpg'),
    (288,'CHINESE CRESTED DOG','Hairless Dogs','CHINA','http://www.fci.be/Nomenclature/Illustrations/288g09.jpg'),
    (289,'ICELANDIC SHEEPDOG','Nordic Watchdogs and Herders','ICELAND','http://www.fci.be/Nomenclature/Illustrations/289g05.jpg'),
    (290,'BEAGLE HARRIER','Scent hounds','FRANCE',NULL),
    (291,'EURASIAN','Asian Spitz and related breeds','GERMANY','http://www.fci.be/Nomenclature/Illustrations/291g05.jpg'),
    (292,'DOGO ARGENTINO','Molossian type','ARGENTINA','http://www.fci.be/Nomenclature/Illustrations/292g02.jpg'),
    (293,'AUSTRALIAN KELPIE','Sheepdogs','AUSTRALIA','http://www.fci.be/Nomenclature/Illustrations/293g01.jpg'),
    (294,'OTTERHOUND','Scent hounds','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/294g06.jpg'),
    (295,'HARRIER','Scent hounds','GREAT BRITAIN',NULL),
    (296,'COLLIE SMOOTH','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/296g01.jpg'),
    (297,'BORDER COLLIE','Sheepdogs','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/297g01.jpg'),
    (298,'ROMAGNA WATER DOG','Water Dogs','ITALY','http://www.fci.be/Nomenclature/Illustrations/298g08-1.jpg'),
    (299,'GERMAN HOUND','Scent hounds','GERMANY',NULL),
    (300,'BLACK AND TAN COONHOUND','Scent hounds','UNITED STATES OF AMERICA','http://www.fci.be/Nomenclature/Illustrations/300g06.jpg'),
    (301,'AMERICAN WATER SPANIEL','Water Dogs','UNITED STATES OF AMERICA',NULL),
    (302,'IRISH GLEN OF IMAAL TERRIER','Large and medium sized Terriers','IRELAND',NULL),
    (303,'AMERICAN FOXHOUND','Scent hounds','UNITED STATES OF AMERICA',NULL),
    (304,'RUSSIAN-EUROPEAN LAIKA','Nordic Hunting Dogs','RUSSIA',NULL),
    (305,'EAST SIBERIAN LAIKA','Nordic Hunting Dogs','RUSSIA','http://www.fci.be/Nomenclature/Illustrations/305g05-1.jpg'),
    (306,'WEST SIBERIAN LAIKA','Nordic Hunting Dogs','RUSSIA',NULL),
    (307,'AZAWAKH','Short-haired Sighthounds','MALI','http://www.fci.be/Nomenclature/Illustrations/307g10-1.jpg'),
    (308,'DUTCH SMOUSHOND','Pinscher and Schnauzer type','THE NETHERLANDS',NULL),
    (309,'SHAR PEI','Molossian type','CHINA',NULL),
    (310,'PERUVIAN HAIRLESS DOG','Primitive type','PERU','http://www.fci.be/Nomenclature/Illustrations/310g05.jpg'),
    (311,'SAARLOOS WOLFHOND','Sheepdogs','THE NETHERLANDS','http://www.fci.be/Nomenclature/Illustrations/311g01-1.jpg'),
    (312,'NOVA SCOTIA DUCK TOLLING RETRIEVER','Retrievers','CANADA',NULL),
    (313,'DUTCH SCHAPENDOES','Sheepdogs','THE NETHERLANDS','http://www.fci.be/Nomenclature/Illustrations/313g01.jpg'),
    (314,'NEDERLANDSE KOOIKERHONDJE','Flushing Dogs','THE NETHERLANDS','http://www.fci.be/Nomenclature/Illustrations/314g08-1.jpg'),
    (315,'BROHOLMER','Molossian type','DENMARK','http://www.fci.be/Nomenclature/Illustrations/315g02.jpg'),
    (316,'FRENCH WHITE AND ORANGE HOUND','Scent hounds','FRANCE',NULL),
    (317,'KAI','Asian Spitz and related breeds','JAPAN','http://www.fci.be/Nomenclature/Illustrations/317g05.jpg'),
    (318,'KISHU','Asian Spitz and related breeds','JAPAN','http://www.fci.be/Nomenclature/Illustrations/318g05.jpg'),
    (319,'SHIKOKU','Asian Spitz and related breeds','JAPAN','http://www.fci.be/Nomenclature/Illustrations/319g05.jpg'),
    (320,'WIREHAIRED SLOVAKIAN POINTER','Continental Pointing Dogs','SLOVAKIA',NULL),
    (321,'MAJORCA SHEPHERD DOG','Sheepdogs','SPAIN',NULL),
    (322,'GREAT ANGLO-FRENCH TRICOLOUR HOUND','Scent hounds','FRANCE',NULL),
    (323,'GREAT ANGLO-FRENCH WHITE AND BLACK HOUND','Scent hounds','FRANCE','http://www.fci.be/Nomenclature/Illustrations/323g06.jpg'),
    (324,'GREAT ANGLO-FRENCH WHITE & ORANGE HOUND','Scent hounds','FRANCE',NULL),
    (325,'MEDIUM-SIZED ANGLO-FRENCH HOUND','Scent hounds','FRANCE',NULL),
    (326,'SOUTH RUSSIAN SHEPHERD DOG','Sheepdogs','RUSSIA',NULL),
    (327,'RUSSIAN BLACK TERRIER','Pinscher and Schnauzer type','RUSSIA',NULL),
    (328,'CAUCASIAN SHEPHERD DOG','Molossian type','RUSSIA','http://www.fci.be/Nomenclature/Illustrations/328g02.jpg'),
    (329,'CANARIAN WARREN HOUND','Primitive type - Hunting Dogs','SPAIN','http://www.fci.be/Nomenclature/Illustrations/329g05.jpg'),
    (330,'IRISH RED AND WHITE SETTER','British and Irish Pointers and Setters','IRELAND',NULL),
    (331,'KANGAL SHEPHERD DOG','Molossian type','TURKEY','http://www.fci.be/Nomenclature/Illustrations/331g02.jpg'),
    (332,'CZECHOSLOVAKIAN WOLFDOG','Sheepdogs','SLOVAKIA',NULL),
    (333,'POLISH GREYHOUND','Short-haired Sighthounds','POLAND',NULL),
    (334,'KOREA JINDO DOG','Asian Spitz and related breeds','REPUBLIC OF KOREA','http://www.fci.be/Nomenclature/Illustrations/334g05.jpg'),
    (335,'CENTRAL ASIA SHEPHERD DOG','Molossian type','RUSSIA','http://www.fci.be/Nomenclature/Illustrations/335g02-1.jpg'),
    (336,'SPANISH WATER DOG','Water Dogs','SPAIN',NULL),
    (337,'ITALIAN SHORT-HAIRED SEGUGIO','Scent hounds','ITALY','http://www.fci.be/Nomenclature/Illustrations/337g06.jpg'),
    (338,'THAI RIDGEBACK DOG','Primitive type - Hunting Dogs','THAILAND',NULL),
    (339,'PARSON RUSSELL TERRIER','Large and medium sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/339g03.jpg'),
    (340,'SAINT MIGUEL CATTLE DOG','Molossian type','PORTUGAL',NULL),
    (341,'BRAZILIAN TERRIER','Large and medium sized Terriers','BRAZIL','http://www.fci.be/Nomenclature/Illustrations/341g03.jpg'),
    (342,'AUSTRALIAN SHEPHERD','Sheepdogs','UNITED STATES OF AMERICA',NULL),
    (343,'ITALIAN CANE CORSO','Molossian type','ITALY','http://www.fci.be/Nomenclature/Illustrations/343g02.jpg'),
    (344,'AMERICAN AKITA','Asian Spitz and related breeds','JAPAN',NULL),
    (345,'JACK RUSSELL TERRIER','Small sized Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/345g03-2.jpg'),
    (346,'DOGO CANARIO','Molossian type','SPAIN',NULL),
    (347,'WHITE SWISS SHEPHERD DOG','Sheepdogs','SWITZERLAND','http://www.fci.be/Nomenclature/Illustrations/347g01-1.jpg'),
    (348,'TAIWAN DOG','Primitive type - Hunting Dogs','TAIWAN',NULL),
    (349,'ROMANIAN MIORITIC SHEPHERD DOG','Sheepdogs','ROMANIA',NULL),
    (350,'ROMANIAN CARPATHIAN SHEPHERD DOG','Sheepdogs','ROMANIA','http://www.fci.be/Nomenclature/Illustrations/350g01.jpg'),
    (351,'AUSTRALIAN STUMPY TAIL CATTLE DOG','Cattledogs (except Swiss Cattledogs)','AUSTRALIA',NULL),
    (352,'RUSSIAN TOY','Continental Toy Spaniel and Russian Toy','RUSSIA','http://www.fci.be/Nomenclature/Illustrations/352g09-1.jpg'),
    (353,'CIMARRÓN URUGUAYO','Molossian type','URUGUAY',NULL),
    (354,'POLISH HUNTING DOG','Scent hounds','POLAND',NULL),
    (355,'BOSNIAN AND HERZEGOVINIAN - CROATIAN SHEPHERD DOG','Molossian type','BOSNIA AND HERZEGOVINA, CROATIA',NULL),
    (356,'DANISH-SWEDISH FARMDOG','Pinscher and Schnauzer type','DENMARK, SWEDEN','http://www.fci.be/Nomenclature/Illustrations/356g02.jpg'),
    (357,'ROMANIAN BUCOVINA SHEPHERD','Molossian type','ROMANIA','http://www.fci.be/Nomenclature/Illustrations/357g02.jpg'),
    (358,'THAI BANGKAEW DOG','Asian Spitz and related breeds','THAILAND','http://www.fci.be/Nomenclature/Illustrations/358g05.jpg'),
    (359,'MINIATURE BULL TERRIER','Bull type Terriers','GREAT BRITAIN','http://www.fci.be/Nomenclature/Illustrations/359g03.jpg'),
    (360,'LANCASHIRE HEELER','Sheepdogs','ENGLAND','http://www.fci.be/Nomenclature/Illustrations/360g01.jpg'),
    (361,'SEGUGIO MAREMMANO','Scent hounds','ITALY','http://www.fci.be/Nomenclature/Illustrations/361g06-1.jpg');
